# Use postgres/example user/password credentials
version: "3.1"
services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_LOCAL_PORT}:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"

  redis:
    build:
      dockerfile: redis.Dockerfile
      args:
        REDIS_STORE_PASSWORD: "${REDIS_STORE_PASSWORD}"
    ports:
      - ${REDIS_STORE_LOCAL_PORT}:6379
    restart: always
